exp_name: duie2 # nyt_star, nyt, webnlg_star, webnlg, ace05_lu
data_in_dir: ../ori_data
ori_data_format: tplinker # casrel (webnlg_star, nyt_star), etl_span (webnlg), raw_nyt (nyt), tplinker (see readme)

# if build data for BERT, use these 3 lines and comment the following 2 lines.
encoder: BERT
bert_path: ../../pretrained_models/chinese-bert-wwm-ext-hit #  chinese-bert-wwm-ext-hit, bert-base-cased
data_out_dir: ../data4bert

# # if build data for BiLSTM, use these 2 lines and comment above 3 lines.
# encoder: BiLSTM
# data_out_dir: ../data4bilstm

# if only reproduce the results, no need to change the args below.
# separate_char_by_white: e.g. "$%sdkn839," -> "$% sdkn839 ," , will make original char spans invalid
# add_char_span: set add_char_span to false if it already exists
# ignore_subword: when adding character level spans, match words with whitespace around: " word ", to avoid subword match, set false for chinese
# check_tok_span: check whether there is any error with token spans, if there is, print the unmatch info
add_char_span: true
ignore_subword: false
separate_char_by_white: false
check_tok_span: true
